### ISSUE TITLE
ban

### ISSUE THREAD

**Issue by detecyang** [lanvsblue/AppBrowser#1]
---

**Comment by lanvsblue** [comment]
确实是个问题，等iOS 11的private header出来了，我更新一下

**Comment by gaoliang851** [comment]
我们在iOS 11上进行了测试，发现
NSArray<LSApplicationProxy *> applicationArray = [applicationWorkspace allInstalledApplications]；
该方法中，苹果似乎进行了变动，xcode控制台显示了这个信息：
[default] No results found for query: {(
    <_LSBundleProxiesOfTypeQuery: 0x1c42210a0>
)}

**Comment by app111** [comment]
需要签名entitlements

**Comment by lanvsblue** [comment]
@gaoliang851 iOS beta版往往会有很多API的变动,等到稳定版会好点.如果正式版发布了,发现API有调整,我会想办法修复的,请关注

**Comment by huadaogege** [comment]
现在有解决办法了么

**Comment by huadaogege** [comment]
@app111 需要签名entitlements是什么操作？

**Comment by wangchangfei** [comment]
大神这个问题有解决方法了吗？

**Comment by wengxianxun** [comment]
@lanvsblue  现在方案出来了吗

**Comment by JadeXH** [comment]
1.White list
2.mdm

**Comment by uiue** [comment]
@FuckUmei 什么意思？

**Comment by flynn-z** [comment]
大神们有研究出什么好办法了么
